# Generated by Django 5.0.7 on 2024-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_my_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
