# Generated by Django 5.0.7 on 2024-08-26 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ata_model', '0001_initial'),
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ata',
            name='signature_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atas', to='signatures.signaturelist'),
        ),
    ]
