# Generated by Django 5.0.7 on 2024-08-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturelist',
            name='n_signature',
            field=models.IntegerField(default=0),
        ),
    ]
