name: Testes Automáticos Django

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
jobs:
  testes:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout do Repositório
      uses: actions/checkout@4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Instalando Dependencias
      run: |
        python - m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Rodar Testes
      run: |
        python manage.py test

    - name: Rodar os testes de mutação (que se encontra na feature/test_mutacao)
      if: github.ref == 'refs/heads/feature/test_mutacao'
      run: |
        python py_mutants.py